# Config file for automatic testing at travis-ci.org

# https://docs.travis-ci.com/user/languages/python/
language: python
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  -
# command to install dependencies
install:
  - "pip install ."
  - 
# command to run tests
script: python runtests.py
