# Config file for automatic testing at travis-ci.org

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install ."
# command to run tests
script: python runtests.py
